const actionTypes = {
    GET_MOIVE_LIST:"GET_MOIVE_LIST",
    GET_MOIVE_LIST_START:"GET_MOIVE_LIST_START",
    GET_MOIVE_SUBJECT:"GET_MOIVE_SUBJECT",
    GET_MOIVE_SUBJECT_LOADING:"GET_MOIVE_SUBJECT_LOADING",
    GET_MENULIST_LOADING:"GET_MENULIST_LOADING",
    GET_MENULIST:"GET_MENULIST",
};
export default actionTypes;